# Generated by Django 3.1.5 on 2021-01-17 18:22

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post Başlığı')),
                ('slug', models.SlugField(editable=False, max_length=350, unique=True, verbose_name='Post urlsi')),
                ('author', models.CharField(max_length=200, verbose_name='Yazar')),
                ('row', models.IntegerField(unique=True, verbose_name='Post Sırası')),
                ('post_image', models.ImageField(upload_to='', verbose_name='Post Resmi')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Post Detayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('IsShowHome', models.BooleanField(default=False, verbose_name='Anasayfada Göster')),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at', 'id'],
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kategori Adı')),
                ('row', models.IntegerField(unique=True, verbose_name='Kategori Sırası')),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True, verbose_name='Post Kategorisi urlsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
            ],
            options={
                'verbose_name_plural': 'Post Kategorileri',
                'ordering': ['row', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post Başlığı')),
                ('detail', ckeditor.fields.RichTextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('IsShowHome', models.BooleanField(default=False, verbose_name='Onayla Göster')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Posts.post', verbose_name='Post Seç')),
            ],
            options={
                'verbose_name_plural': 'Post Yorumları',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='post', to='Posts.PostCategory', verbose_name='Kategori Seç'),
        ),
    ]
