# Generated by Django 3.1.5 on 2021-01-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IsReelsVideo',
            field=models.BooleanField(default=False, verbose_name='Reels Göster'),
        ),
        migrations.AddField(
            model_name='post',
            name='IsShowMidSlider',
            field=models.BooleanField(default=False, verbose_name='Anasayfada Orta Slider Göster'),
        ),
        migrations.AddField(
            model_name='post',
            name='IsShowTopSlider',
            field=models.BooleanField(default=False, verbose_name='Anasayfada Üst Slider Göster'),
        ),
    ]
