# Generated by Django 3.1.5 on 2021-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20210118_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reels_video',
            field=models.ImageField(null=True, upload_to='', verbose_name='Video Reels'),
        ),
    ]
