# Generated by Django 3.1.5 on 2021-01-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_post_reels_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reels_video',
            field=models.FileField(null=True, upload_to='', verbose_name='Video Reels'),
        ),
    ]
