# Generated by Django 3.1.5 on 2021-01-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_auto_20210118_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='IsShowMenu',
            field=models.BooleanField(default=False, verbose_name='Menüde Göster'),
        ),
    ]
