# Generated by Django 3.1.5 on 2021-01-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_postcategory_isshowmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='IsReelsVideo',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('R', 'Reels'), ('P', 'Post'), ('S', 'Story'), ('O', 'Diğer')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='IsShowHome',
            field=models.BooleanField(default=False, verbose_name='Banner Slider Göster'),
        ),
    ]
