# Generated by Django 3.1.5 on 2021-01-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20210122_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='IsShowHome',
            field=models.BooleanField(default=False, verbose_name='Anasayfada Göster'),
        ),
    ]
