# Generated by Django 3.1.5 on 2021-01-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_post_advertisement_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='advertisement_banner',
        ),
    ]
