# Generated by Django 3.1.5 on 2021-01-23 20:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0010_remove_post_advertisement_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Post Başlığı')),
                ('detail', ckeditor.fields.RichTextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('IsShowHome', models.BooleanField(default=False, verbose_name='Onayla Göster')),
            ],
            options={
                'verbose_name_plural': 'Post Yorumları',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
