# Generated by Django 3.1.5 on 2021-01-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0012_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttags',
            name='detail',
        ),
        migrations.AddField(
            model_name='posttags',
            name='row',
            field=models.IntegerField(default=1, unique=True, verbose_name='Etiket Sırası'),
            preserve_default=False,
        ),
    ]
